apps/vacations/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
    url(r'^lists/', views.vacation_list, name='vacation_list'),
    url(r'^mylist/', views.vacation_mylist, name='vacation_mylist'),
    url(r'^teamlist/', views.vacation_teamlist, name='vacation_teamlist'),
    url(r'^create/', views.vacation_create, name='vacation_create'),
    url(r'^detail/', views.vacation_detail, name='vacation_detail'),
    url(r'^mydetail/', views.my_vacation_detail, name='my_vacation_detail'),
    url(r'^agree/', views.agree, name='vacation_agree'),
    url(r'^denied/', views.denied, name='vacation_denied'),
    url(r'^vacation_check', views.vacation_check, name='vacation_check'),
    url(r'^select_users', views.select_users, name='select_users'),
]

company_manager/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from apps.users import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/login/', auth_views.login, name='login', kwargs={'template_name': 'registration/login.html'}),
    url(r'^accounts/logout/$', auth_views.logout, {'next_page' : '/accounts/login'}, name='logout'),
    url(r'^accounts/signup$', views.signup, name='signup'),
    url(r'^users/', include('apps.users.urls')),
    url(r'^vacations/', include('apps.vacations.urls')),

]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

apps/vacations/models.py
from django.db import models
from django.conf import settings
from apps.users.models import MyUser, Agent, Grant


class Vacation(models.Model):

    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.PROTECT,
        verbose_name='유저'
    )
    vacation_type = models.ForeignKey(
        'VacationCode',
        verbose_name='연차 종류',
        null=False,
        blank=False
    )
    start = models.DateField(
        verbose_name='연차 시작'
    )
    end = models.DateField(
        verbose_name='연차 끝'
    )
    first_approval = models.CharField(
        max_length=2,
        default='',
        verbose_name='첫 승인 여부'
    )
    last_approval = models.CharField(
        max_length=2,
        default='',
        verbose_name='마지막 승인 여부'
    )
    reason = models.TextField(
        verbose_name='사유'
    )
    created = models.DateTimeField(
        auto_now_add=True,
        verbose_name='생성일'
    )
    updated = models.DateTimeField(
        auto_now=True,
        verbose_name='수정일'
    )
    first_approval_user = models.ForeignKey(
        MyUser,
        verbose_name='1차 승인자',
        null=True,
        blank=True,
        related_name='first_approval_user'
    )
    last_approval_user = models.ForeignKey(
        MyUser,
        verbose_name='최종 승인자',
        null=True,
        blank=True,
        related_name='last_approval_user'
    )


    class Meta:
        db_table = 'vacations'
        verbose_name = '연차'
        verbose_name_plural = '연차들'

    def __str__(self):
        return str(self.user)


class VacationCode(models.Model):
    codename = models.CharField(
        max_length=10,
        verbose_name='연차 명'
    )

    minus_day = models.FloatField(
        verbose_name='차감일수'
    )

    class Meta:
        db_table='vacation_code'

    def __str__(self):
        return self.codename

apps/vacations/forms.py
from django import forms
from .models import Vacation, VacationCode
from apps.users.models import MyUser, Grant


class CreateVacationFrom(forms.ModelForm):
    vacation_type = forms.ModelChoiceField(
        required=True,
        label="신청 구분",
        queryset=VacationCode.objects.all(),
        widget=forms.Select(
            attrs={
                'class': 'form-control',
                'required' : 'True'
            }
        )
    )

    start = forms.DateField(
        required=True,
        label="휴가 시작일",
        widget=forms.DateInput(
            attrs={
                'class': 'form-control datepicker',
                'required' : 'True'
            }
        )
    )

    end = forms.DateField(
        required=True,
        label="휴가 종료일",
        widget=forms.DateInput(
            attrs={
                'class': 'form-control datepicker',
                'required' : 'True'
            }
        )
    )

    reason = forms.CharField(
        required=True,
        label="사유",
        widget=forms.Textarea(
            attrs={
                'class':'form-control',
                'required' : 'True'
            }
        )
    )

    first_approval_user = forms.ModelChoiceField(
        label="1차 승인자",
        queryset=MyUser.objects.all(),
        widget=forms.Select(
            attrs={
                'class': 'form-control',
            }
        )
    )

    last_approval_user = forms.ModelChoiceField(
        label="최종 승인자",
        queryset=MyUser.objects.all(),
        widget=forms.Select(
            attrs={
                'class': 'form-control'
            }
        )
    )

    class Meta:
        model = Vacation
        fields = ("vacation_type", "start", "end", "reason", "first_approval_user", "last_approval_user")

apps/vacations/views.py
from django.shortcuts import render
from django.conf import settings
from django.db.models import Q
from django.http import JsonResponse
from apps.users.models import MyUser, Grant, Agent
from apps.teams.models import Team
from .models import VacationCode
from django.db.models import Subquery, OuterRef
import datetime
import json

from .forms import CreateVacationFrom
from .models import Vacation


def vacation_list(request):
    object = Vacation.objects.select_related().all()
    return render(request, "vacation_list.html", {'vacation_list': object})


def vacation_mylist(request):
    object = Vacation.objects.select_related().filter(user_id=request.user.uid)
    return render(request, "my_vacation_list.html", {'vacation_list': object})


def vacation_teamlist(request):
    object = Vacation.objects.select_related().filter(Q(first_approval_user=request.user.uid) | Q(last_approval_user=request.user.uid))
    return render(request, "vacation_list.html", {'vacation_list': object})


def vacation_create(request):
    vacationform = CreateVacationFrom()
    if request.method == 'POST':
        vacationform = CreateVacationFrom(request.POST)
        vacationform.first_approval_user = request.POST['first_approval_user']
        vacationform.last_approval_user = request.POST['last_approval_user']
        if vacationform.is_valid():
            vacation = vacationform.save(commit=False)
            vacation.user_id = request.user.uid
            vacation.save()
            users = MyUser.objects.get(uid=vacation.user_id)
            minus_day = VacationCode.objects.get(id=vacation.vacation_type_id)
            if minus_day.id == 1:
                minus_days = (vacation.start - vacation.end) * minus_day.minus_day
                users.v_day = users.v_day + minus_days.days
            else:
                users.v_day = users.v_day - minus_day.minus_day
            users.save()

    first_approval = None
    team_id = MyUser.objects.get(uid=request.user.uid).team_id
    team_master = Team.objects.get(tid=team_id).team_master_id
    grant_obj = Grant.objects.get(user_id=team_master)
    if grant_obj is not None:
        if grant_obj.agent_id is not None:
            now_date = datetime.datetime.now().strftime('%Y-%m-%d')
            if datetime.datetime.strptime(str(grant_obj.agent.start), '%Y-%m-%d') <= datetime.datetime.strptime(str(now_date), '%Y-%m-%d') <= datetime.datetime.strptime(str(grant_obj.agent.end), '%Y-%m-%d'):
                first_approval = {'user_id': grant_obj.agent.user_id, 'user_nm': grant_obj.agent.user.name}
            else:
                first_approval = {'user_id': grant_obj.user_id, 'user_nm': grant_obj.user.name}
        else:
            first_approval = {'user_id': grant_obj.user_id, 'user_nm': grant_obj.user.name}
    else:
        first_approval = None

    last_approval = None
    team_master2 = Team.objects.get(tid=team_id).upper_team.team_master_id
    grant_obj2 = Grant.objects.get(user_id=team_master2)
    if grant_obj2 is not None:
        if grant_obj2.agent_id is None:
            last_approval = {'user_id':grant_obj2.user_id, 'user_nm' : grant_obj2.user.name}
        else:
            last_approval = {'user_id':grant_obj2.agent.user_id, 'user_nm' : grant_obj2.agent.user.name}
    else:
        last_approval = None

    return render(request, "register_vacation.html", {'vacationform': vacationform, 'first_approval': first_approval, 'last_approval':last_approval})


def vacation_check(request):
    vacation_check = Vacation.objects.filter(Q(user_id=request.user.uid) & (Q(start__range=(request.POST['start'], request.POST['end'])) | Q(end__range=(request.POST['start'], request.POST['end'])))).count()
    if vacation_check > 0:
        return JsonResponse({'result':'FAIL'})
    else:
        return JsonResponse({'result':'SUCCESS'})


def vacation_detail(request):
    object = Vacation.objects.select_related().get(user_id=request.POST['user_uid'], id=request.POST['v_id'])
    return render(request, "vacation_detail.html", {'info': object, 'flag':'all'})


def my_vacation_detail(request):
    object = Vacation.objects.select_related().get(id=request.POST['v_id'])
    return render(request, "vacation_detail.html", {'info': object, 'flag': 'my'})


def agree(request):
    v_id = request.POST.get('v_id')
    object = Vacation.objects.get(pk=v_id)
    if object.first_approval_user.uid == request.user.uid:
        object.first_approval = 'Y'
        object.save()
    elif object.last_approval_user.uid == request.user.uid:
        object.last_approval = 'Y'
        object.save()
    return JsonResponse({'result':'SUCCESS'})


def denied(request):
    v_id = request.POST.get('v_id')
    object = Vacation.objects.get(pk=v_id)
    if object.first_approval_user.uid == request.user.uid:
        object.first_approval = 'N'
        object.save()
    elif object.last_approval_user.uid == request.user.uid:
        object.last_approval = 'N'
        object.save()
    return JsonResponse({'result':'SUCCESS'})


def select_users(request):
    object = Grant.objects.select_related().annotate(
        agent_nm=Subquery(Agent.objects.select_related().filter(id=OuterRef('agent_id')).values('user__name')),
        agent_id=Subquery(Agent.objects.filter(id=OuterRef('agent_id')).values('user__uid')),
        start=Subquery(Vacation.objects.filter(user_id=OuterRef('user_id'), first_approval='Y', last_approval='Y').values('start')),
        end=Subquery(Vacation.objects.filter(user_id=OuterRef('user_id'), first_approval='Y', last_approval='Y').values('end'))
    ).all()
    return render(request, 'select_users.html', {'user_list': object, 'now_date' : datetime.datetime.today()})

apps/vacations/templates/my_vacation_list.html
{% extends 'base.html' %}
{% block content %}
    <div style="margin-top: 70px">
    <h3>{{ request.user.name }}님 연차 리스트</h3>
    <p>잔여 연차일수 : {{ request.user.v_day }} 일</p>
    <button class="btn btn-default" onclick="location.href='{% url 'vacation_create' %}'">연차 신청</button>
        <table class="table">
            <thead>
                <th>번호</th>
                <th>연차종류</th>
                <th>신청일</th>
                <th>상태</th>
            </thead>
            <tbody>
            {% for list in vacation_list %}
                <tr onclick="detail_form('{{ list.id }}')">
                    <td>{{ list.id }}</td>
                    <td>{{ list.vacation_type.codename }}</td>
                    <td>{{ list.created }}</td>
                    <td>
                        {% if list.first_approval == "" %}
                            신청
                        {% elif list.first_approval == "Y" and list.last_approval == "" %}
                            1차 승인
                        {% elif list.first_approval != "Y" and list.last_approval != "Y" %}
                            승인
                        {% elif list.first_approval == "N" or list.last_approval == "N" %}
                            반려
                        {% endif %}
                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>

    <form id="detail_form" action="{% url 'my_vacation_detail' %}" method="post">
    {% csrf_token %}
        <input type="hidden" id="v_id" name="v_id">
    </form>

    <script>
    function detail_form(v_id) {
        $('#v_id').val(v_id);
        $('#detail_form').submit();
    }
    </script>

{% endblock %}

apps/vacations/templates/register_vacation.html
{% extends 'base.html' %}
{% block content %}
    <section style="margin-top: 70px">
			<form method="post" action="{% url 'vacation_create' %}" id="frm">
                {% csrf_token %}
                <div class="col-md-6 col-md-push-3">
                    <div class="form-group">
                        {{ vacationform.vacation_type.label_tag }}
                        {{ vacationform.vacation_type }}
				    </div>

                    <div class="form-group">
                        {{ vacationform.start.label_tag }}
                        {{ vacationform.start}}
				    </div>

                    <div class="form-group">
                        {{ vacationform.end.label_tag }}
                        {{ vacationform.end }}
				    </div>


                    <div class="form-group">
                        {{ vacationform.reason.label_tag }}
                        {{ vacationform.reason }}
                    </div>

                    <div class="form-group">
                        {{ vacationform.first_approval_user.label_tag }}
                        <button class="btn btn-default" type="button" onclick="popup_approval('first')">선택</button>
                        <input type="hidden" name="first_approval_user" id="id_first_approval_user" value="{{ first_approval.user_id }}">
                        <input type="text" id="id_first_approval_user_name" disabled class="form-control" value="{{ first_approval.user_nm }}">
                    </div>

                    <div class="form-group">
                        {{ vacationform.last_approval_user.label_tag }}
                        <button class="btn btn-default" type="button" onclick="popup_approval('last')">선택</button>
                        <input type="hidden" name="last_approval_user" id="id_last_approval_user" value="{{ last_approval.user_id }}">
                        <input type="text" id="id_last_approval_user_name" disabled class="form-control" value="{{ last_approval.user_nm }}">
                    </div>
                    <input type="hidden" id="flag">
                    <button type="button" name="go" class="btn btn-primary btn-block" onclick="check_submit();">생성</button>
                    <button type="button" name="go" class="btn btn-danger btn-block" onclick="location.href='/user_manager/list'">취소</button>
                </div>
			</form>
		</section>
    <script>
    $(function () {
        $('.datepicker').datepicker({
            dateFormat : 'yy-mm-dd'
        });
    });

    function popup_approval(flag) {
        $('#flag').val(flag);
        var popUrl = "{% url 'select_users' %}";
        var popOption = "width=400, height=600";
        var openWin;
        openWin = window.open(popUrl, "", popOption);

    }

    function check_submit() {
        var data = {'start' : $('#id_start').val(), 'end':$('#id_end').val(), 'csrfmiddlewaretoken':'{{ csrf_token }}'};
        $.ajax({
            url : "{% url 'vacation_check' %}",
            data : data,
            dataType : 'json',
            type : 'POST',
            success : function (data) {
                if(data.result == "SUCCESS"){
                    alert('신청되었습니다.');
                    $('#frm').submit();
                }else{
                    alert('일정이 중복되었습니다.');
                }
            }
        })
    }
    </script>
{% endblock %}

apps/vacations/templates/select_users.html
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>

<input type="hidden" id="flag">
<table>
    <thead>
        <th>이름</th>
        <th>상태</th>
        <th>대리인</th>
    </thead>
    <tbody>
        {% for list in user_list %}
            <tr onclick="
                    {% if list.agent_id == None %}
                        setValue('{{ list.user_id }}', '{{ list.user.name }}')
                    {% else %}
                        setValue('{{ list.agent_id }}', '{{ list.agent_nm }}')
                    {% endif %}
                    ">
                <td>{{ list.user.name }}</td>
                <td>
                {% if list.start != None and list.end != None %}
                    {% if now_date|date >= list.start|date or now_date <= list.end|date %}
                        휴가중
                    {% endif %}
                {% endif %}
                </td>
                <td>{{ list.agent_nm|default:'' }}</td>
            </tr>
        {% endfor %}
    </tbody>
</table>

<script>
    $(function () {
       $('#flag').val(opener.document.getElementById("flag").value);
    });
    function setValue(user_id, user_nm) {
        if($('#flag').val() == 'first'){
            opener.document.getElementById('id_first_approval_user_name').value = user_nm;
            opener.document.getElementById('id_first_approval_user').value = user_id;
        }else{
            opener.document.getElementById('id_last_approval_user_name').value = user_nm;
            opener.document.getElementById('id_last_approval_user').value = user_id;
        }
    }
</script>

apps/vacations/templates/vacation_detail.html
{% extends 'base.html' %}
{% block content %}
    <section style="margin-top: 70px">
        <input type="hidden" id="pk" value="{{ info.pk }}">
        <div class="form-group">
            <label>이름</label>
            <h4>{{ info.user.name }}</h4>
        </div>

        <div class="form-group">
            <label>신청구분</label>
            <h4>{{ info.vacation_type.codename }}</h4>
        </div>

        <div class="form-group">
            <label>휴가 시작일</label>
            <h4>{{ info.start }}</h4>
        </div>

        <div class="form-group">
            <label>휴가 종료일</label>
            <h4>{{ info.end }}</h4>
        </div>

        <div class="form-group">
            <label>사유</label>
            <h4>{{ info.reason }}</h4>
        </div>

        <div class="form-group">
        {% if flag == 'all' %}
            {% if info.first_approval == 'N' or info.last_approval == 'N' %}
                <h4>반려된 신청입니다.</h4>
            {% elif info.first_approval_user_id == request.user.uid and info.first_approval == 'Y' %}
                <h4>1차 승인한 신청입니다.</h4>
            {% else %}
                <button name="agree" id="agree" class="btn btn-default" onclick="agree()">승인</button>
                <button name="denied" id="denied" class="btn btn-danger" onclick="denied()">반려</button>
            {% endif %}
        {% endif %}

        {% if flag == 'my' %}
            <button name="cancel" id="cancel" class="btn btn-danger" onclick="cancel()">취소</button>
        {% endif %}

        </div>
    </section>

    <script>
    function agree() {
        if(confirm('승인하시겠습니까?') == true){

            $.ajax({
                url: "/vacations/agree/",
                type : "POST",
                data : {'v_id' : $('#pk').val(), 'csrfmiddlewaretoken':'{{ csrf_token }}' },
                dataType : "json",
                success : function (data) {
                    if(data.result == 'SUCCESS'){
                        alert('승인되었습니다');
                    }
                }
            })
        }

    }

    function denied() {
        if(confirm('반려하시겠습니까?') == true){
            $.ajax({
                url: "/vacations/denied/",
                type : "POST",
                data : {'v_id' : $('#pk').val(), 'csrfmiddlewaretoken':'{{ csrf_token }}' },
                dataType : "json",
                success : function (data) {
                    if(data.result == 'SUCCESS'){
                        alert('반려되었습니다');
                    }
                }
            })
        }
    }
    
    function cancel() {
        if(confirm('취소하시겠습니까?') == true){
            $.ajax({
                url: "/vacations/cancel/",
                type : "POST",
                data : {'v_id' : $('#pk').val(), 'csrfmiddlewaretoken':'{{ csrf_token }}' },
                dataType : "json",
                success : function (data) {
                    if(data.result == 'SUCCESS'){
                        alert('반려되었습니다');
                    }
                }
            })
        }
    }

    </script>
{% endblock %}

apps/vacations/templates/vacation_list.html
{% extends 'base.html' %}
{% block content %}
    <div style="margin-top: 70px">
    <h3>직원 연차 리스트</h3>
        <table class="table">
            <thead>
                <th>번호</th>
                <th>이름</th>
                <th>연차종류</th>
                <th>신청일</th>
                <th>상태</th>
            </thead>
            <tbody>
            {% for list in vacation_list %}
                <tr onclick="detail_form('{{ list.id }}', '{{ list.user.uid }}')">
                    <td>{{ list.id }}</td>
                    <td>{{ list.user.name }}</td>
                    <td>{{ list.vacation_type.codename }}</td>
                    <td>{{ list.created }}</td>
                    <td>
                        {% if list.first_approval == "" %}
                            신청
                        {% elif list.first_approval == "Y" and list.last_approval == "" %}
                            1차 승인
                        {% elif list.first_approval == "Y" and list.last_approval == "Y" %}
                            승인
                        {% elif list.first_approval == "N" or list.last_approval == "N" %}
                            반려
                        {% endif %}
                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>

    <form id="detail_form" action="{% url 'vacation_detail' %}" method="post">
    {% csrf_token %}
        <input type="hidden" id="v_id" name="v_id">
        <input type="hidden" id="user_uid" name="user_uid">
    </form>

    <script>
    function detail_form(v_id, user_uid) {
        $('#v_id').val(v_id);
        $('#user_uid').val(user_uid);
        $('#detail_form').submit();
    }
    </script>

{% endblock %}

apps/vacations/templates/vacation_modify.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

apps/vacations/templates/vacation_register.html
{% extends 'base.html' %}
{% block content %}
    <div style="margin-top: 70px">
    <h3>연차 신청</h3>
        <div class="row">
            <form action="" method="post">
                {% csrf_token %}
                <div class="form-group">
                <select name="type_cd" class="form-control">
                    <option value="">신청분류</option>
                    {% for list in type_code %}
                        <option value="{{ list.cd }}">{{ list.cd_nm }}</option>
                    {% endfor %}
                </select>
            </div>

            <div class="form-group">
                <label for="sta_dt">시작일</label>
                <input type="date" id="sta_dt" name="sta_dt">
            </div>
            <div class="form-group">
                <label for="end_dt">종료일</label>
                <input type="date" id="end_dt" name="end_dt">
            </div>
            <div class="form-group">
                <label for="reason">신청사유</label>
                <textarea class="form-control" id="reason" name="reason"></textarea>
            </div>
                <button class="btn btn-default" type="submit">신청</button>
                <button class="btn btn-danger" type="button">취소</button>
            </form>
        </div>

    </div>
{% endblock %}